export const AUTHENTICATION_STATUS_REQUESTED =
  "AUTHENTICATION_STATUS_REQUESTED";
export const AUTHENTICATION_STATUS_SUCCESS = "AUTHENTICATION_STATUS_SUCCESS";
export const AUTHENTICATION_STATUS_FAILURE = "AUTHENTICATION_STATUS_FAILURE";
